language: java
jdk: oraclejdk7
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - sudo apt-get install expect
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq libstdc++6:i386 lib32z1; fi
  - wget -O android-sdk.tgz http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz
  - tar xzf android-sdk.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - chmod +x $PWD/.travis_install_android.sh
  - $PWD/.travis_install_android.sh

  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd ./maven-android-sdk-deployer/
  - mvn install -P4.2
  - cd ..

  # Create and start emulator
  - echo no | android create avd --force -n Default -t android-17 --abi armeabi-v7a
  - emulator -avd Default -no-skin -no-audio -no-window &

before_script:
  - chmod +x $PWD/.travis_wait_for_emulator.sh
  - $PWD/.travis_wait_for_emulator.sh

script: mvn install -Pwith-tests