language: java
jdk: oraclejdk7

before_install:
  - chmod +x $PWD/.travis_install_android.sh
  - $PWD/.travis_install_android.sh

  - chmod +x $PWD/.travis_install_android_dependencies.sh
  - $PWD/.travis_install_android_dependencies.sh

  - chmod +x $PWD/.travis_start_emulator.sh
  - $PWD/.travis_start_emulator.sh

before_script:
  - chmod +x $PWD/.travis_wait_for_emulator.sh
  - $PWD/.travis_wait_for_emulator.sh

script: mvn install -Pwith-tests