before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- chmod +x $PWD/.travis_install_android.sh
- $PWD/.travis_install_android.sh
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- chmod +x $PWD/.travis_install_android_dependencies.sh
- $PWD/.travis_install_android_dependencies.sh
- chmod +x $PWD/.travis_start_emulator.sh
- $PWD/.travis_start_emulator.sh
before_script:
- chmod +x $PWD/.travis_wait_for_emulator.sh
- $PWD/.travis_wait_for_emulator.sh
jdk: oraclejdk7
language: java
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: mvn install -Pwith-tests
